services:
  apt:
    image: ghcr.io/doridian/apt-mirror-docker/apt-mirror:latest
    restart: never
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - "/mnt/zhdd/mirror/apt:/var/spool/apt-mirror"
  apt-web:
    image: ghcr.io/doridian/apt-mirror-docker/nginx:latest
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.13
    mac_address: 02:40:12:6c:d7:1a
    volumes:
      - "/mnt/zhdd/mirror/apt/mirror:/mirror:ro"
