services:
  agent:
    image: ghcr.io/doridian/hashtopolis-docker/agent:cuda-latest
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: all
             capabilities: [gpu]
    healthcheck:
      test: '(nvidia-smi -L | grep -qF "GPU 0") || exit 1'
      interval: 60s
      timeout: 10s
