services:
  plex:
    image: plexinc/pms-docker:latest
    restart: always
    runtime: nvidia
    labels:
      net.doridian.nvidia-check: true
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.3
    mac_address: 00:16:3E:CA:7E:03
    environment:
      PLEX_UID: 10001
      PLEX_GID: 1001
      ALLOWED_NETWORKS: 10.0.0.0/8
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - plex_data:/config
      - /mnt/zssd/docker/plex/transcode:/transcode
      - /mnt/zhdd/nas:/data
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:32400/web/index.html" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  plex_data: {}
