services:
  samba:
    build: samba
    restart: always
    hostname: nas.foxden.network
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.1
    mac_address: 00:16:3E:CA:7E:04
    volumes:
      - samba_config:/var/lib/samba
      - /mnt/zhdd/nas:/mnt/nas
      - /mnt/zssd/nas/torrent:/mnt/nas/torrent
      - /mnt/zhdd/nashome:/home
      - /mnt/zhdd/timemachine:/mnt/timemachine
    healthcheck:
      test: '/etc/healthcheck.sh >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  samba_config: {}
