services:
  query-finder:
    restart: always
    image: ghcr.io/doridian/query-finder/query-finder:latest
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.11
    volumes:
      - /mnt/zssd/docker/query-finder/.env:/opt/app/.env:ro
      - /mnt/zssd/docker/query-finder/status.jsom:/opt/app/status.json
