services:
  query-finder:
    restart: always
    image: ghcr.io/doridian/query-finder/query-finder:latest
    init: true
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.11
    environment:
      TZ: America/Los_Angeles
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:8988/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
      - config:/config

volumes:
  config: {}
