services:
  query-finder:
    restart: always
    image: ghcr.io/doridian/query-finder/query-finder:latest
    init: true
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.11
    volumes:
      - config:/config

volumes:
  config: {}
