services:
  syncthing:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      PUID: 1000
      PGID: 1000
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.2
    mac_address: ae:fc:dd:8b:33:76
  webdav:
    build: webdav
    restart: always
    init: true
    network_mode: service:syncthing
    environment:
      WEBDAV_PASSWORD_DORIDIAN: ${WEBDAV_PASSWORD_DORIDIAN}
    volumes:
    - webdav_config:/config
    - webdav_data:/data
    - data:/syncthing
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  data: {}
  webdav_config: {}
  webdav_data: {}

