services:
    backup:
        image: kopia/kopia:latest
        hostname: backup.foxden.network
        restart: always
        environment:
            KOPIA_PASSWORD: ${KOPIA_PASSWORD}
            KOPIA_WEB_PASSWORD: ${KOPIA_WEB_PASSWORD}
            TZ: America/Los_Angeles
        volumes:
            - kopia_config:/app/config
            - kopia_cache:/app/cache
            - kopia_logs:/app/logs
        command: ["server", "start", "--insecure", "--address=0.0.0.0:51515", "--tls-cert-file /app/config/tls.crt", "--tls-key-file /app/config/tls.key", "--server-username=doridian", "--server-password=${KOPIA_WEB_PASSWORD}"]

volumes:
  kopia_config: {}
  kopia_cache: {}
  kopia_logs: {}
