services:
  dldr:
    build: dldr
    restart: always
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.default.src_valid_mark=1
      - net.ipv4.conf.lo.src_valid_mark=1
      - net.ipv4.conf.eth0.src_valid_mark=1
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.8
    environment:
      VPN_CLIENT: wireguard
      VPN_PROV: custom
      VPN_ENABLED: 'yes'
      LAN_NETWORK: 10.0.0.0/8
      PUID: 1001
      PGID: 1001
      TZ: America/Los_Angeles
    volumes:
      - deluge_config:/config
      - /mnt/zssd/nas/torrent:/data
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:8112/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
  dldr-prometheus:
    image: tobbez/deluge_exporter:latest
    restart: always
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.10
    environment:
      DELUGE_HOST: dldr
    links:
      - dldr:dldr
    volumes:
      - deluge_config:/root/.config/deluge:ro
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    environment:
      PUID: 1001
      PGID: 1001
      TZ: America/Los_Angeles
      NZBGET_USER: nzbget
      NZBGET_PASS: ${NZBGET_PASSWORD}
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.9
    volumes:
      - nzbget_config:/config
      - /mnt/zssd/nas/usenet:/downloads
    restart: always
volumes:
  deluge_config: {}
  nzbget_config: {}
