services:
  dldr:
    build: dldr
    restart: always
    links:
      - bitmagnet-postgres:bitmagnet-postgres
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.default.src_valid_mark=1
      - net.ipv4.conf.lo.src_valid_mark=1
      - net.ipv4.conf.eth0.src_valid_mark=1
    environment:
      VPN_CLIENT: wireguard
      VPN_PROV: custom
      VPN_ENABLED: 'yes'
      LAN_NETWORK: 10.0.0.0/8
      TZ: America/Los_Angeles
    volumes:
      - deluge_config:/config
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:8112/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
  dldr-prometheus:
    image: tobbez/deluge_exporter:latest
    restart: always
    network_mode: service:dldr
    init: true
    environment:
      DELUGE_HOST: 127.0.0.1
      HOME: /home/user
      LISTEN_PORT: 9100
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:9100/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
      - deluge_config:/home/user/.config/deluge:ro
  nzbget:
    image: linuxserver/nzbget:latest
    environment:
      TZ: America/Los_Angeles
      NZBGET_USER: nzbget
      NZBGET_PASS: ${NZBGET_PASSWORD}
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 6789 || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
      - nzbget_config:/config
    restart: always
volumes:
  deluge_config: {}
  nzbget_config: {}
