services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: always
    environment:
      TZ: America/Los_Angeles
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/zhdd/nas:/media
  jellyfin-web:
    build: jellyfin-web
    restart: always
    network_mode: service:jellyfin
    volumes:
      - jellyfin_web_data:/data
      - jellyfin_web_config:/config
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 80 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  jellyfin_config: {}
  jellyfin_web_data: {}
  jellyfin_web_config: {}
  jellyfin_cache: {}
