services:
  plex:
    image: plexinc/pms-docker:latest
    restart: always
    environment:
      PLEX_UID: 10001
      ALLOWED_NETWORKS: 10.0.0.0/8
      TZ: America/Los_Angeles
    volumes:
      - plex_config:/config
      - /mnt/zhdd/nas:/data

volumes:
  plex_config: {}
