services:
  plex:
    image: plexinc/pms-docker:latest
    restart: always
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: all
             capabilities: [gpu]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.3
    mac_address: 00:16:3E:CA:7E:03
    environment:
      PLEX_UID: 10001
      PLEX_GID: 1001
      ALLOWED_NETWORKS: 10.0.0.0/8
      TZ: America/Los_Angeles
    volumes:
      - plex_config:/config
      - /mnt/zssd/docker/plex/transcode:/transcode
      - /mnt/zhdd/nas:/data
    healthcheck:
      test: '(curl -s -f "http://$${HOSTNAME}:32400/web/index.html" >/dev/null && (nvidia-smi -L | grep -qF "GPU 0")) || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  plex_config: {}
