services:
  web:
    build: web
    userns_mode: host
    restart: always
    volumes:
      - /mnt/zhdd/nas:/mnt/nas:ro
      - /mnt/zhdd/mirror:/mnt/mirror:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  caddy_data: {}
  caddy_config: {}
