services:
  web:
    build: web
    restart: always
    volumes:
      - /mnt/zhdd/nas:/mnt/nas:ro
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  caddy_data: {}
  caddy_config: {}
