services:
  web:
    build: web
    restart: always
    volumes:
      - /mnt/zhdd/nas:/mnt/nas:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - NAS_WEB_DOMAIN
    ports:
      - 10.2.11.1:80:80
      - 10.2.11.1:443:443
      - 10.2.11.1:443:443/udp
    port_mode_ports:
      - 80:80
      - 443:443
      - 443:443/udp
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  caddy_data: {}
  caddy_config: {}
