services:
  syncthing:
    image: linuxserver/syncthing:latest
    restart: always
    ports:
      - 8384:8384
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - config:/config
      - data:/data1
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 8384 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  config: {}
  data: {}
