version: "3"
services:
  portainer:
    image: "portainer/portainer-ce:latest"
    ports:
      - "8000:8000"
      - "9000:9000"
    userns_mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
volumes:
  portainer_data:
    name: portainer_data
