services:
  rsync:
    user: 10000:10000
    build: rsync
    restart: always
    init: true
    network_mode: service:web
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 873 || exit 1'
      interval: 60s
      timeout: 10s
