services:
  web:
    user: 10000:10000
    build: web
    restart: always
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - src: archzfs
        dst: /mnt/archmirror/other/archzfs
        volumeSubpath: repo
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  caddy_data: {}
  caddy_config: {}
