services:
  gogs:
    image: gogs/gogs:latest
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.2
    environment:
      SOCAT_LINK: "false"
    volumes:
      - gogs_data:/data
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:3000/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
  gogs-web:
    build: gogs-web
    restart: always
    network_mode: service:gogs
    volumes:
      - gogs_web_data:/data
      - gogs_web_config:/config
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  gogs_data: {}
  gogs_web_data: {}
  gogs_web_config: {}
