services:
  aurbuild:
    build: aurbuild
    restart: always
    init: true
    devices:
      - /dev/yk4:/dev/yk4
    environment:
      GPG_KEY_ID: "723AB072D36DF76677DA5ACF41ADC5FF876838A8"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist:ro
      - /etc/makepkg.conf:/etc/makepkg.conf:ro
