services:
  aurbuild:
    build: aurbuild
    restart: always
    init: true
    volumes:
      - gpg:/gpg:ro
      - /run/pcscd:/run/pcscd
      - /etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist:ro
      - /etc/makepkg.conf:/etc/makepkg.conf:ro

volumes:
  gpg: {}
