services:
  aurbuild:
    build: aurbuild
    restart: always
    init: true
    environment:
      GPG_KEY_ID: "${GPG_KEY_ID}"
      GPG_KEY_PATH: /gpg/foxdenaur.asc
    volumes:
      - cache:/aur/cache
      - gpg:/gpg:ro

volumes:
  cache: {}
  gpg: {}
