defaults:
  routes:
    http: 127.0.0.1:8080
    https: 127.0.0.1:8443
  ports:
    http: 80
    https: 443
aliases:
  nas: 10.2.11.1
  homeassistant: 10.2.12.2
  gmod-nginx: 10.3.10.5
  foxcaves: 10.3.10.1
hosts:
  nas.foxden.network:
    target: nas
  homeassistant.foxden.network:
    target: homeassistant
  syncthing.doridian.net:
    target: webdav
  api.spaceage.mp:
    target: gmod-nginx
  spaceage.mp:
    target: gmod-nginx
  static.spaceage.mp:
    target: gmod-nginx
  tts.spaceage.mp:
    target: gmod-nginx
  www.spaceage.mp:
    target: gmod-nginx
  forums.spaceage.mp:
    target: gmod-nginx
  foxcav.es:
    target: foxcaves
  www.foxcav.es:
    target: foxcaves
  f0x.es:
    target: foxcaves
  www.f0x.es:
    target: foxcaves
