defaults:
  routes:
    http: 127.0.0.1:8080
    https: 127.0.0.1:8443
  ports:
    http: 80
    https: 443
hosts:
  nas.foxden.network:
    target: 10.2.11.1
  homeassistant.foxden.network:
    target: 10.2.12.2
  syncthing.doridian.net:
    target: webdav
  api.spaceage.mp:
    target: 10.3.10.5
  spaceage.mp:
    target: 10.3.10.5
  static.spaceage.mp:
    target: 10.3.10.5
  tts.spaceage.mp:
    target: 10.3.10.5
  www.spaceage.mp:
    target: 10.3.10.5
  forums.spaceage.mp:
    target: 10.3.10.5
  