version: "2.4"
services:
  homeserver:
    image: matrixconduit/matrix-conduit:latest
    restart: always
    volumes:
      - homeserver_data:/srv/conduit/.local/share/conduit
    environment:
      CONDUIT_SERVER_NAME: doridian.net
      CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
      CONDUIT_ALLOW_REGISTRATION : 'true'
      CONDUIT_ADDRESS: 0.0.0.0
      CONDUIT_PORT: 8008
      CONDUIT_CONFIG: ''  # if you want to configure purely by env vars, set this to an empty string ''
      # Available levels are: error, warn, info, debug, trace - more info at: https://docs.rs/env_logger/*/env_logger/#enabling-logging
      CONDUIT_LOG: info
      CONDUIT_ALLOW_JAEGER: 'false'
      CONDUIT_ALLOW_ENCRYPTION: 'true'
      CONDUIT_ALLOW_FEDERATION: 'true'
      CONDUIT_DATABASE_PATH: /srv/conduit/.local/share/conduit
      CONDUIT_WORKERS: 10
      CONDUIT_MAX_REQUEST_SIZE: 50_000_000
  nginx:
    build: nginx
    init: true
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default: {}
      vlan2:
        ipv4_address: 192.168.2.30
    links:
      - homeserver:homeserver
    volumes:
      - certbot_www:/var/www/certbot:ro
      - certbot_certs:/etc/letsencrypt:ro
  certbot:
    image: certbot/certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt

volumes:
  homeserver_data: {}
  certbot_www: {}
  certbot_certs: {}
