services:
  wekan:
    image: quay.io/wekan/wekan
    restart: always
    environment:
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://db:27017/wekan
      - ROOT_URL=https://tasks.foxden.network
      - MAIL_URL=smtp://localhost:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <wekan@foxden.network>
      - RESULTS_PER_PAGE=20
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - files:/data:rw
  web:
    build: caddy
    restart: always
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    links:
      - wekan:wekan
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.8

volumes:
  files: {}
  caddy_data: {}
  caddy_config: {}
