---

services:
  kanidm:
    build: kanidm
    restart: always
    hostname: auth.foxden.network
    environment:
      TZ: America/Los_Angeles
    volumes:
      - kanidm:/data
      - certs:/certs:ro

volumes:
  kanidm: {}
