---

services:
  radius:
    image: ghcr.io/doridian/oauth-jit-radius/oauth-jit-radius:latest
    restart: always
    network_mode: service:kanidm
    user: 1000:1000
    environment:
      TZ: America/Los_Angeles
      TLS_CERT: /certs/live/auth.foxden.network/fullchain.pem
      TLS_KEY: /certs/live/auth.foxden.network/privkey.pem
      OAUTH_TOKEN_URL: https://auth.foxden.network/application/o/token/
      OAUTH_USERINFO_URL: https://auth.foxden.network/application/o/userinfo/
      OAUTH_SCOPES: 'openid profile'
    volumes:
      - certs:/certs:ro
    env_file:
      - .env.foxradius
