services:
  rfcat-mqtt:
    image: ghcr.io/foxdenhome/rfcat-mqtt/rfcat-mqtt:latest
    restart: always
    init: yes
    devices:
      - /dev/RFCAT3:/dev/RFCAT3:rwm
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      RFCAT_MQTT_USERNAME: ${RFCAT_MQTT_USERNAME}
      RFCAT_MQTT_PASSWORD: ${RFCAT_MQTT_PASSWORD}
      RFCAT_MQTT_BROKER: homeassistant.foxden.network
      RFCAT_MQTT_TOPIC: rfcat_mqtt/control
    healthcheck:
      test: 'wget --spider -q "http://127.0.0.1:8080" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
