version: "2"
services:
  prometheus:
    image: prom/prometheus:latest
    command: --storage.tsdb.retention.time=1y --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_data:/data
    networks:
      monitoring_net: {}
      vlan3:
        ipv4_address: 192.168.3.34
    links:
      - telegraf:telegraf
      - telegraf:telegraf.foxden.network
    extra_hosts:
      - ntp.foxden.network:192.168.3.10
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
    volumes:
      - grafana_config:/etc/grafana
      - grafana_data:/var/lib/grafana
    links:
      - prometheus:prometheus
      - prometheus:prometheus.foxden.network
      - grafana-renderer:grafana-renderer
      - grafana-renderer:grafana-renderer.foxden.network
    networks:
      monitoring_net: {}
      vlan3:
        ipv4_address: 192.168.3.35
  grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    links:
      - grafana:grafana
      - grafana:grafana.foxden.network
    networks:
      monitoring_net: {}
  telegraf:
    image: telegraf:latest
    volumes:
      - telegraf_config:/etc/telegraf
    networks:
      monitoring_net: {}
      vlan1:
        ipv4_address: 192.168.1.33

networks:
  monitoring_net: {}

volumes:
  prometheus_config:
    external: true
  prometheus_data:
    external: true
  grafana_config:
    external: true
  grafana_data:
    external: true
  telegraf_config:
    external: true
