services:
  api:
    image: ghcr.io/foxdenhome/e621dumper/e621dumper:latest
    restart: always
    links:
      - elasticsearch:elasticsearch
    environment:
      PUID: 10000
      PGID: 10000
    volumes:
      - config:/config
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:8001/api/v1/healthcheck" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  config: {}
