services:
  elasticsearch:
    image: elasticsearch:8.1.0
    restart: always
    environment:
      discovery.type: single-node
      network.host: _site_
      network.bind_host: _site_
      xpack.security.enabled: 'false'
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:9200/_cat/health" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
    - /mnt/zhdd/zssd/e621/db:/usr/share/elasticsearch/data
