services:
  scrypted:
    image: koush/scrypted:latest
    hostname: scrypted.foxden.network
    restart: always
    environment:
      TZ: America/Los_Angeles
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - data:/server/volume

volumes:
  data: {}
