services:
  scrypted:
    build: scrypted
    hostname: scrypted.foxden.network
    restart: always
    environment:
      TZ: America/Los_Angeles
      SCRYPTED_DOCKER_AVAHI: 'true'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - data:/server/volume

volumes:
  data: {}
