services:
  factorio:
    image: nginx:alpine
    restart: always
    networks:
      default:
        priority: 1
    volumes:
      - /mnt/tmpfs/factorio-script-output/graftorio2:/usr/share/nginx/html/graftorio2:ro
