services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_SERVER_ROOT_URL: https://grafana.foxden.network/
      GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: 'true'
      #GF_AUTH_ANONYMOUS_ENABLED: 'true'
      #GF_AUTH_ANONYMOUS_ORG_NAME: FoxDen
      #GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      TZ: America/Los_Angeles
    volumes:
      - grafana_data:/var/lib/grafana
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        priority: 1
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.5
        mac_address: 7e:18:e9:41:a9:6c
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:3000/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
  grafana-web:
    build: grafana-web
    restart: always
    network_mode: service:grafana
    volumes:
      - grafana_web_data:/data
      - grafana_web_config:/config
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
  grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    restart: always
    environment:
      TZ: America/Los_Angeles
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:8081/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  grafana_data: {}
  grafana_web_data: {}
  grafana_web_config: {}
