services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_SERVER_ROOT_URL: http://grafana.foxden.network:3000/
      TZ: America/Los_Angeles
    volumes:
      - grafana_data:/var/lib/grafana
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        priority: 1
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.5
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:3000/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
  grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    restart: always
    environment:
      TZ: America/Los_Angeles
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:8081/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  grafana_data: {}
