services:
  mktxp:
    build: mktxp
    restart: always
    environment:
      MTIK_USERNAME: ${MTIK_USERNAME}
      MTIK_PASSWORD: ${MTIK_PASSWORD}
    extra_hosts:
      - router.foxden.network:10.6.1.1
      - router-backup.foxden.network:10.6.1.3
    networks:
      default:
        priority: 1
      vlan6:
        priority: 100
        ipv4_address: 10.6.11.3
        mac_address: 02:58:ac:5e:17:8a
