services:
  prometheus:
    build: prometheus
    restart: always
    command: --storage.tsdb.retention.time=1y --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - prometheus_data:/prometheus
    environment:
      TZ: America/Los_Angeles
      HOMEASSISTANT_API_TOKEN: ${PROMETHEUS_HOMEASSISTANT_API_TOKEN}
    links:
      - telegraf:telegraf
      - telegraf:telegraf.foxden.network
    extra_hosts:
      - ntp.foxden.network:10.2.1.2
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:9090/-/healthy" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  prometheus_data: {}
