services:
  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    userns_mode: host
    privileged: true
  prometheus:
    build: prometheus
    restart: always
    command: --storage.tsdb.retention.time=1y --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - prometheus_data:/prometheus
    environment:
      TZ: America/Los_Angeles
      HOMEASSISTANT_API_TOKEN: ${PROMETHEUS_HOMEASSISTANT_API_TOKEN}
    links:
      - telegraf:telegraf
      - telegraf:telegraf.foxden.network
      - islandfox.foxden.network:node-exporter
    extra_hosts:
      - ntp.foxden.network:10.6.1.2
    networks:
      default:
        priority: 1
      vlan6:
        priority: 100
        ipv4_address: 10.6.11.1
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:9090/-/healthy" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  prometheus_data: {}
