services:
  telegraf:
    build: telegraf
    restart: always
    command: --config-directory /etc/telegraf/includes
    environment:
      TZ: America/Los_Angeles
      SNMP_COMMUNITY: ${SNMP_COMMUNITY}
    networks:
      default:
        priority: 1
      vlan6:
        priority: 100
        ipv4_address: 10.6.11.2
    healthcheck:
      test: 'curl -f -s http://${HOSTNAME}:9273/metrics | grep -q '^snmp_' || exit 1'
      interval: 60s
      timeout: 10s
