services:
  telegraf:
    build: telegraf
    restart: always
    command: --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/includes
    environment:
      TZ: America/Los_Angeles
      SNMP_COMMUNITY: ${SNMP_COMMUNITY}
    networks:
      default:
        priority: 1
      vlan6:
        priority: 100
        ipv4_address: 10.6.11.2
        mac_address: 42:fe:0c:c8:e0:f5
    extra_hosts:
      - ntp.foxden.network:10.6.1.2
      - router.foxden.network:10.6.1.1
      - router-backup.foxden.network:10.6.1.3
      - icefox.doridian.net:10.99.10.2
    healthcheck:
      test: 'curl -f -s "http://$${HOSTNAME}:9273/metrics" | grep -q "^snmp_" || exit 1'
      interval: 60s
      timeout: 10s
