services:
  telegraf:
    build: telegraf
    restart: always
    command: --config-directory /etc/telegraf/includes
    environment:
      TZ: America/Los_Angeles
      SNMP_COMMUNITY: ${SNMP_COMMUNITY}
    networks:
      default:
        priority: 1
      vlan1:
        priority: 100
        ipv4_address: 10.1.13.1
    extra_hosts:
      wired: 10.101.11.1
      lte: 10.101.11.2
      internet: 8.8.8.8
      router: 10.1.1.1
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:9273/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
