services:
  caddy:
    build: caddy
    restart: always
    networks:
      internal_network:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.9
    depends_on:
      - web
      - static
      - streaming
      - crossposter-web
    links:
      - web:web
      - static:static
      - streaming:streaming
      - crossposter-web:crossposter-web
    volumes:
      - caddy_config:/config
      - caddy_data:/data

volumes:
  caddy_data: {}
  caddy_config: {}
