services:
  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      internal_network:
        priority: 1
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

volumes:
  postgres_data: {}
