services:
  sidekiq:
    image: ghcr.io/doridian/mastodon-docker/mastodon-docker
    restart: always
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      internal_network:
        priority: 1
      default:
        priority: 100
    env_file: .env.mastodon
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
