services:
  prosody:
    build: prosody
    restart: always
    hostname: f0x.es
    environment:
      DOMAIN: f0x.es
      TZ: America/Los_Angeles
    volumes:
    - prosody_config:/usr/local/etc/prosody
    - prosody_letsencrypt:/etc/letsencrypt
    - prosody_data:/usr/local/var/lib/prosody
  slidcord:
    image: nicocool84/slidcord:master
    restart: always
    hostname: discord.f0x.es
    command:
    - "--server"
    - "f0x.es"
    - "--user-jid-validator"
    - ".*@f0x.es"
    - "--jid"
    - "discord.f0x.es"
    - "--secret"
    - "${SLIDCORD_SECRET}"
    links:
    - prosody:f0x.es
    - prosody:xmppshare.f0x.es
    environment:
      TZ: America/Los_Angeles
    volumes:
    - slidcord_data:/var/lib/slidge
  slidgram:
    image: nicocool84/slidgram:master
    restart: always
    hostname: telegram.f0x.es
    command:
    - "--server"
    - "f0x.es"
    - "--user-jid-validator"
    - ".*@f0x.es"
    - "--jid"
    - "telegram.f0x.es"
    - "--secret"
    - "${SLIDGRAM_SECRET}"
    links:
    - prosody:f0x.es
    - prosody:xmppshare.f0x.es
    environment:
      TZ: America/Los_Angeles
    volumes:
    - slidgram_data:/var/lib/slidge

volumes:
  prosody_config: {}
  prosody_letsencrypt: {}
  prosody_data: {}

  slidcord_data: {}
  slidgram_data: {}
