services:
  prosody:
    build: prosody
    restart: always
    hostname: foxden.network
    environment:
      LOG_LEVEL: info
      SLIDCORD_SECRET: ${SLIDCORD_SECRET}
      SLIDGRAM_SECRET: ${SLIDGRAM_SECRET}
      TZ: America/Los_Angeles
    volumes:
    - prosody_certs:/usr/local/etc/prosody/certs
    - prosody_letsencrypt:/etc/letsencrypt
    - prosody_data:/usr/local/var/lib/prosody
  slidcord:
    build: slidcord
    restart: always
    hostname: discord.xmpp.foxden.network
    command:
    - "--server"
    - "foxden.network"
    - "--user-jid-validator"
    - ".*@foxden.network"
    - "--jid"
    - "discord.xmpp.foxden.network"
    - "--debug"
    links:
    - prosody:foxden.network
    - prosody:xmpp.foxden.network
    - prosody:upload.xmpp.foxden.network
    environment:
      TZ: America/Los_Angeles
      SLIDGE_SECRET: ${SLIDCORD_SECRET}
      DISCORD_VERBOSE: true
    volumes:
    - slidcord_data:/var/lib/slidge
  slidgram:
    image: nicocool84/slidgram:master
    restart: always
    hostname: telegram.xmpp.foxden.network
    command:
    - "--server"
    - "foxden.network"
    - "--user-jid-validator"
    - ".*@foxden.network"
    - "--jid"
    - "telegram.xmpp.foxden.network"
    links:
    - prosody:foxden.network
    - prosody:xmpp.foxden.network
    - prosody:upload.xmpp.foxden.network
    environment:
      TZ: America/Los_Angeles
      SLIDGE_SECRET: ${SLIDGRAM_SECRET}
      API_ID: ${TELEGRAM_API_ID}
      API_HASH: ${TELEGRAM_API_HASH}
    volumes:
    - slidgram_data:/var/lib/slidge

volumes:
  prosody_certs: {}
  prosody_letsencrypt: {}
  prosody_data: {}

  slidcord_data: {}
  slidgram_data: {}
