services:
  slidgram:
    image: nicocool84/slidgram:master
    restart: always
    hostname: telegram.xmpp.foxden.network
    command:
    - "--server"
    - "foxden.network"
    - "--user-jid-validator"
    - ".*@foxden\\.network"
    - "--jid"
    - "telegram.xmpp.foxden.network"
    links:
    - prosody:foxden.network
    - prosody:xmpp.foxden.network
    - prosody:upload.xmpp.foxden.network
    environment:
      TZ: America/Los_Angeles
      SLIDGE_SECRET: ${SLIDGRAM_SECRET}
      API_ID: ${TELEGRAM_API_ID}
      API_HASH: ${TELEGRAM_API_HASH}
    volumes:
    - slidgram_data:/var/lib/slidge

volumes:
  slidgram_data: {}
