services:
  web:
    ports:
      - 10.2.11.1:80:80
      - 10.2.11.1:443:443
      - 10.2.11.1:443:443/udp
    environment:
      NAS_WEB_DOMAIN: nas.foxden.network
  dldr:
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.8
    mac_address: ca:1b:f1:2c:6c:b3
    volumes:
      - /mnt/zhdd/nas/torrent:/data
    environment:
      PUID: 1001
      PGID: 1001
  dldr-prometheus:
    user: 1001:1001
  nzbget:
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.9
    mac_address: f2:73:89:cc:9e:e4
    environment:
      PUID: 1001
      PGID: 1001
    volumes:
      - /mnt/zhdd/nas/usenet:/downloads
  kiwix:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.6
    mac_address: 00:16:3E:CA:7E:01
    volumes:
      - /mnt/zhdd/kiwix:/data
  plex:
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: all
             capabilities: [gpu]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.3
    mac_address: 00:16:3E:CA:7E:03
    environment:
      PLEX_GID: 1001
    volumes:
      - /mnt/zhdd/docker/plex/transcode:/transcode
    healthcheck:
      test: '(curl -s -f "http://$${HOSTNAME}:32400/web/index.html" >/dev/null && (nvidia-smi -L | grep -qF "GPU 0")) || exit 1'
      interval: 60s
      timeout: 10s
  s3:
    environment:
      MINIO_BROWSER_REDIRECT_URL: https://console.s3.foxden.network
      MINIO_SERVER_URL: https://s3.foxden.network
    hostname: s3.foxden.network
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.17
    mac_address: d2:5b:0f:b8:77:26
    volumes:
      - /mnt/zhdd/s3:/data
  s3-web:
    build:
      args:
        S3_BASE: s3.foxden.network
