services:
  kiwix:
    volumes:
      - /mnt/ztank/kiwix:/data
  router:
    build: _overrides/router
    restart: always
    init: true
    ports:
    - 80:80
    - 443:443
    links:
    - web:web
    - s3:s3
    extra_hosts:
    - host.docker.internal:host-gateway
  web:
    environment:
      NAS_WEB_DOMAIN: nas-ro.foxden.network
  plex:
    environment:
      PLEX_GID: 1003
    ports:
      - 32400:32400
    volumes:
      - /mnt/local/docker/plex/transcode:/transcode
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:32400/web/index.html" >/dev/null'
      interval: 60s
      timeout: 10s
  dldr:
    environment:
      PUID: 1003
      PGID: 1003
    volumes:
      - /mnt/local/torrent:/data
  dldr-prometheus:
    user: 1003:1003
  nzbget:
    environment:
      PUID: 1003
      PGID: 1003
    volumes:
      - /mnt/local/usenet:/downloads
  s3:
    environment:
      MINIO_BROWSER_REDIRECT_URL: https://console.s3.doridian.net
      MINIO_SERVER_URL: https://s3.doridian.net
    volumes:
      - /mnt/ztank/s3:/data
  s3-web:
    build:
      args:
        S3_BASE: s3.doridian.net
