---

services:
  ldap:
    image: ghcr.io/goauthentik/ldap:2024.8.0
    restart: always
    network_mode: service:server
    environment:
      AUTHENTIK_HOST: http://127.0.0.1:81/
      AUTHENTIK_INSECURE: 'false'
      AUTHENTIK_HOST_BROWSER: ''
      AUTHENTIK_TOKEN: ${LDAP_AUTHENTIK_TOKEN}
      SSL_CERT_DIR: /etc/ssl/certs
      AUTHENTIK_LISTEN__METRICS: 127.0.0.1:9301
      AUTHENTIK_LISTEN__LDAPS: ':636'
      AUTHENTIK_LISTEN__LDAP: ':389'
