---

services:
  ldap:
    image: ghcr.io/goauthentik/radius:2024.8.0
    restart: always
    network_mode: service:server
    environment:
      TZ: America/Los_Angeles
      AUTHENTIK_HOST: http://127.0.0.1:81/
      AUTHENTIK_INSECURE: 'false'
      AUTHENTIK_HOST_BROWSER: ''
      AUTHENTIK_TOKEN: ${RADIUS_AUTHENTIK_TOKEN}
      SSL_CERT_DIR: /etc/ssl/certs
      AUTHENTIK_LISTEN__METRICS: 127.0.0.1:9302
      AUTHENTIK_LISTEN__RADIUS: ':1812'
