services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${FOXCAVES_POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: su postgres -c pg_isready
      interval: 60s
      timeout: 10s

volumes:
  postgres: {}
