services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli PING
      interval: 60s
      timeout: 10s

volumes:
  redis: {}
