services:
  site:
    image: ghcr.io/foxcaves/site/foxcaves-site:latest
    restart: always
    environment:
      ENVIRONMENT: production
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.1
    mac_address: 00:16:3E:CA:7E:00
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - config:/var/www/foxcaves/config
      - ssl:/etc/letsencrypt
      - /mnt/zhdd/foxcaves/storage:/var/www/foxcaves/storage
    healthcheck:
      test: 'curl -s -f --insecure "https://$${HOSTNAME}/api/v1/system/info" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  config: {}
  ssl: {}
