services:
  site:
    image: ghcr.io/foxcaves/site/foxcaves-site:latest
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      ENVIRONMENT: production
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.1
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - config:/var/www/foxcaves/config
      - ssl:/etc/letsencrypt
      - storage:/var/www/foxcaves/storage
    healthcheck:
      test: 'curl -s -f --resolve "foxcav.es:443:127.0.0.1" "https://foxcav.es/api/v1/system/info" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  config: {}
  ssl: {}
  storage: {}
