version: "2.4"
services:
  syncthing:
    image: linuxserver/syncthing:latest
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      vlan4:
        ipv4_address: 192.168.4.21
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - config:/config
      - data:/data1
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 8384 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  config: {}
  data: {}
