version: "2.4"
services:
  syncthing:
    image: linuxserver/syncthing:latest
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      vlan4:
        ipv4_address: 192.168.4.21
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - syncthing_config:/config
      - /mnt/zhdd/syncthing:/data1

volumes:
  syncthing_config:
    external: true
