global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'prometheus.foxden.network'

  - job_name: node
    static_configs:
      - targets: ['bengalfox.foxden.network:9100', 'islandfox.foxden.network:9100', 'ntp.foxden.network:9100']

  - job_name: telegraf
    static_configs:
      - targets: ['telegraf:9273']

  - job_name: homeassistant
    scrape_interval: 60s
    metrics_path: /api/prometheus
    authorization:
      credentials: '${HOMEASSISTANT_API_TOKEN}'
    scheme: https
    static_configs:
      - targets: ['homeassistant.foxden.network:443']
  