version: "2.4"
services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_SERVER_ROOT_URL: http://grafana.foxden.network:3000/
    volumes:
      - grafana_config:/etc/grafana
      - grafana_data:/var/lib/grafana
    networks:
      default: {}
      vlan3:
        ipv4_address: 192.168.3.35
  grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    restart: always

volumes:
  grafana_config:
    external: true
  grafana_data:
    external: true
