version: "2.4"
services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_RENDERING_SERVER_URL: http://grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_SERVER_ROOT_URL: http://grafana.foxden.network:3000/
      TZ: America/Los_Angeles
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      default: {}
      vlan3:
        ipv4_address: 192.168.3.35
    healthcheck:
      test: 'curl -s -f "http://$(hostname):3000/" >/dev/null || exit 1'
      interval: 5s
      timeout: 3s
  grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    restart: always
    environment:
      TZ: America/Los_Angeles

volumes:
  grafana_data:
    external: true
