version: "2.4"
services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    command: --storage.tsdb.retention.time=1y --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      monitoring_net: {}
      vlan3:
        ipv4_address: 192.168.3.34
    links:
      - telegraf:telegraf
      - telegraf:telegraf.foxden.network
      - minico2:minico2
      - minico2:minico2.foxden.network
    extra_hosts:
      - ntp.foxden.network:192.168.3.10

volumes:
  prometheus_config:
    external: true
  prometheus_data:
    external: true
