version: "2.4"
services:
  telegraf:
    build: telegraf
    restart: always
    command: --config-directory /etc/telegraf/includes
    hostname: telegraf.foxden.network
    environment:
      TZ: America/Los_Angeles
    networks:
      default: {}
      vlan1:
        ipv4_address: 192.168.1.33
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:9273/" >/dev/null || exit 1'
      interval: 5s
      timeout: 3s
