version: "2.4"
services:
  telegraf:
    build: telegraf
    restart: always
    command: --config-directory /etc/telegraf/includes
    environment:
      TZ: America/Los_Angeles
    networks:
      default: {}
      vlan1:
        ipv4_address: 192.168.1.33
