services:
  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    restart: always
    environment:
      - TZ=America/Los_Angeles
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
