services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      # Put your personal gluetun/VPN account config and credentials here:
      # (See https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers)
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    restart: always
    networks:
      default:
        ipv4_address: 192.168.69.11
    extra_hosts:
      - "bitmagnet:192.168.55.11"
      - "postgres:192.168.55.12"

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.69.0/24
