services:
  snirouter:
    build: snirouter
    restart: always
    init: true
    networks:
      default:
        priority: 100
      ext:
        priority: 10
        ipv4_address: 192.168.69.1

networks:
  ext:
    ipam:
      driver: default
      config:
        - subnet: 192.168.69.0/24
          ip_range: 192.168.69.0/24
          gateway: 192.168.69.254
