defaults:
  backends:
    http:
      host: 127.0.0.1
      port: 9998
    https:
      host: 127.0.0.1
      port: 9999
templates:
  archive.ubuntu.com:
    https:
      host: archive.ubuntu.com
      host_passthrough: true
      port: 443
  security.ubuntu.com:
    https:
      host: security.ubuntu.com
      host_passthrough: true
      port: 443
  ports.ubuntu.com:
    https:
      host: ports.ubuntu.com
      host_passthrough: true
      port: 443
  deb.debian.org:
    https:
      host: deb.debian.org
      host_passthrough: true
      port: 443
hosts:
  archive.ubuntu.com:
    template: archive.ubuntu.com
  _.archive.ubuntu.com:
    template: archive.ubuntu.com
  security.ubuntu.com:
    template: security.ubuntu.com
  _.security.ubuntu.com:
    template: security.ubuntu.com
  ports.ubuntu.com:
    template: ports.ubuntu.com
  _.ports.ubuntu.com:
    template: ports.ubuntu.com
  deb.debian.org:
    template: deb.debian.org
  _.deb.debian.org:
    template: deb.debian.org
