services:
  dldr:
    build: dldr
    restart: always
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.default.src_valid_mark=1
      - net.ipv4.conf.lo.src_valid_mark=1
      - net.ipv4.conf.eth0.src_valid_mark=1
    ports:
      - 8080:80
    environment:
      VPN_CLIENT: wireguard
      VPN_PROV: custom
      VPN_ENABLED: 'yes'
      LAN_NETWORK: 10.0.0.0/8
      PUID: 1003
      PGID: 1003
      TZ: America/Los_Angeles
    volumes:
      - deluge_config:/config
      - /mnt/ephemeral/nas/tmp/torrent:/data
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:8112/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    ports:
      - 8081:80
    environment:
      PUID: 1003
      PGID: 1003
      TZ: America/Los_Angeles
      NZBGET_USER: nzbget
      NZBGET_PASS: ${NZBGET_PASSWORD}
    volumes:
      - nzbget_config:/config
      - /mnt/ephemeral/nas/tmp/usenet:/downloads
    restart: always
volumes:
  deluge_config: {}
  nzbget_config: {}
