services:
  plex:
    image: plexinc/pms-docker:latest
    restart: always
    ports:
      - 32400:32400
    environment:
      PLEX_UID: 10001
      PLEX_GID: 1003
      ALLOWED_NETWORKS: 10.0.0.0/8
      TZ: America/Los_Angeles
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - /mnt/ephemeral/nas/zhdd/nas:/data
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:32400/web/index.html" >/dev/null'
      interval: 60s
      timeout: 10s

volumes:
  plex_config: {}
  plex_transcode: {}
