services:
  samba:
    build: samba
    restart: always
    hostname: nas-ro.foxden.network
    userns_mode: host
    ports:
      - 0.0.0.0:137:137
      - 0.0.0.0:138:138
      - 0.0.0.0:139:139
      - 0.0.0.0:445:445
    volumes:
      - ssl:/etc/letsencrypt
      - samba_config:/var/lib/samba
      - /mnt/ephemeral/nas/zhdd/nashome:/home
      - /mnt/ephemeral/nas/zhdd/nas:/mnt/nas
      - /mnt/ephemeral/nas/tmp:/mnt/tmp
    healthcheck:
      test: 'smbstatus -S -f'
      interval: 60s
      timeout: 10s

volumes:
  samba_config: {}
