services:
  samba:
    build: samba
    restart: always
    hostname: nas-ro.foxden.network
    userns_mode: host
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ssl:/etc/letsencrypt
      - samba_config:/var/lib/samba
      - /mnt/ephemeral/nas/zhdd/nashome:/home
      - /mnt/ephemeral/nas/zhdd/nas:/mnt/nas
    healthcheck:
      test: 'smbstatus -S -f'
      interval: 60s
      timeout: 10s

volumes:
  samba_config: {}
