services:
  web:
    build: web
    restart: always
    volumes:
      - /mnt/ephemeral/nas/zhdd/nas:/mnt/nas:ro
      - /mnt/ephemeral/nas/tmp:/mnt/tmp:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    links:
      - samba:samba
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  caddy_data: {}
  caddy_config: {}
