version: "2.4"
services:
  kiwix:
    image: kiwix/kiwix-serve:latest
    restart: always
    init: yes
    command: '*.zim'
    networks:
      vlan2:
        ipv4_address: 192.168.2.20
    healthcheck:
      test: 'curl -s -f "http://`hostname`/" >/dev/null || exit 1'
      interval: 5s
      timeout: 3s
    volumes:
      - /mnt/zhdd/kiwix:/data
