services:
  agent:
    image: ghcr.io/doridian/hashtopolis-docker:cuda
    restart: always
    environment:
      BASE_URL: https://htpl.foxden.network
      KEY_TYPE: apikey
      KEY_VALUE: ${HASHTOPOLIS_KEY}
