services:
  agent:
    image: ghcr.io/doridian/hashtopolis-docker/agent:please-select-tag
    restart: always
    init: true
    environment:
      BASE_URL: https://htpl.foxden.network
      KEY_TYPE: apikey
      KEY_VALUE: ${HASHTOPOLIS_KEY}
    volumes:
    - agent:/opt/agent

volumes:
  agent: {}
