version: "2.4"
services:
  samba:
    build: image
    restart: always
    hostname: nas.foxden.network
    networks:
      vlan4:
        ipv4_address: 192.168.4.20
    volumes:
      - samba_config:/var/lib/samba
      - /mnt/zhdd/nas:/mnt/nas
      - /mnt/zssd/nas/torrent:/mnt/nas/torrent
      - /mnt/zhdd/nashome:/home
      - /mnt/zhdd/timemachine:/mnt/timemachine

volumes:
  samba_config:
    external: true
