version: "2.4"
services:
  mdns-repeater:
    image: ghcr.io/doridian/docker-mdns-repeater/mdns-repeater:latest
    restart: always
    command: eth0 eth1 eth2
    networks:
      vlan3:
        ipv4_address: 192.168.3.4
      vlan4:
        ipv4_address: 192.168.4.4
      vlan5:
        ipv4_address: 192.168.5.4
