defaults:
  backends:
    http:
      host: host.docker.internal
      port: 80
    https:
      host: host.docker.internal
      port: 443
templates:
  nas:
    http:
      host: host.docker.internal
      port: 180
    https:
      host: host.docker.internal
      port: 543
  syncthing:
    http:
      host: host.docker.internal
      port: 181
    https:
      host: host.docker.internal
      port: 544
  jellyfin:
    http:
      host: host.docker.internal
      port: 182
    https:
      host: host.docker.internal
      port: 545

hosts:
  icefox.doridian.net:
    template: nas
  nas-ro.foxden.network:
    template: nas

  jellyfin.foxden.network:
    template: jellyfin

  syncthing.doridian.net:
    template: syncthing
