services:
  backend:
    build: backend
    restart: always
    links:
      - elasticsearch:elasticsearch
    environment:
      PUID: 10000
      PGID: 10000
      ES_URL: http://elasticsearch:9200
      FA_COOKIE_A: ${FA_COOKIE_A}
      FA_COOKIE_B: ${FA_COOKIE_B}
      PORT: 127.0.0.1:8001
    volumes:
      - backend_config:/config
    healthcheck:
      test: 'curl -s -f "http://127.0.0.1:8001/api/v1/healthcheck" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  backend_config: {}
