services:
  backend:
    image: ghcr.io/doridian/fadumper/backend:latest
    restart: always
    links:
      - elasticsearch:elasticsearch
    environment:
      PUID: 10000
      PGID: 1001
      ES_URL: http://elasticsearch:9200
      FA_COOKIE_A: ${FA_COOKIE_A}
      FA_COOKIE_B: ${FA_COOKIE_B}
      PROXY_URL: ${PROXY_URL}
      FETCHNEW_CONCURRENCY: ${FETCHNEW_CONCURRENCY}
      FETCHNEW_PER_FETCH_LIMIT: ${FETCHNEW_PER_FETCH_LIMIT}
      DOWNLOADFILES_CONCURRENCY: ${DOWNLOADFILES_CONCURRENCY}
    volumes:
      - /mnt/zhdd/furaffinity/data:/data
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:8001/api/v1/healthcheck" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
