services:
  backend:
    image: ghcr.io/doridian/fadumper/backend:latest
    restart: always
    links:
      - elasticsearch:elasticsearch
    environment:
      PUID: 10000
      PGID: 1001
      FA_COOKIE_A: ${FA_COOKIE_A}
      FA_COOKIE_B: ${FA_COOKIE_B}
    volumes:
      - /mnt/zhdd/furaffinity/data:/data
    healthcheck:
      test: 'rm -f /etc/periodic/daily/looper ; curl -s -f "http://$${HOSTNAME}:8001/api/v1/healthcheck" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
