services:
  steam-headless:
    build: steam
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    security_opt:
      - seccomp=steam/seccomp.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    shm_size: 2G
    environment:
      SIZEW: 1920
      SIZEH: 1080
      REFRESH: 60
      DPI: 96
      CDEPTH: 24
      VIDEO_PORT: DFP -e PASSWD=mypasswd -e WEBRTC_ENCODER=nvh264enc -e BASIC_AUTH_PASSWORD=mypasswd -p 8080:8080 ghcr.io/selkies-project/nvidia-glx-desktop:latest
      PASSWD: ${STEAM_USER_PASSWORD}
      BASIC_AUTH_PASSWORD: ${STEAM_USER_PASSWORD}
      WEBRTC_ENCODER: nvh264enc
      TZ: America/Los_Angeles
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.12
    mac_address: 96:4a:9f:c8:c6:b9
    volumes:
      - /mnt/zhdd/steam/home:/home/user:rw
      - /mnt/zhdd/steam/games:/mnt/games:rw
