services:
  steam-headless:
    build: steam
    hostname: steam-docker
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    security_opt:
      - seccomp=steam/seccomp.json
      - apparmor=docker-bwrap
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1
    tmpfs:
      - /run:exec,nosuid,nodev,size=512M
      - /tmp:exec,nosuid,nodev,size=4G
    shm_size: 2G
    environment:
      SIZEW: 3840
      SIZEH: 2160
      REFRESH: 60
      DPI: 96
      CDEPTH: 24
      VIDEO_PORT: DP-0
      PASSWD: ${STEAM_USER_PASSWORD}
      BASIC_AUTH_PASSWORD: ${STEAM_WEB_PASSWORD}
      WEBRTC_ENCODER: nvh264enc
      TZ: America/Los_Angeles
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.12
    mac_address: 96:4a:9f:c8:c6:b9
    volumes:
      - /mnt/zhdd/steam/home:/home/user:rw
      - /mnt/zhdd/steam/games:/mnt/games:rw
