services:
  steam-headless:
    build: steam
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    security_opt:
      - seccomp=seccomp.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/tty7:/dev/tty7
    shm_size: 2G
    environment:
      NAME: SteamHeadless
      TZ: America/Los_Angeles
      USER_LOCALES: en_US.UTF-8 UTF-8
      DISPLAY: :55
      SHM_SIZE: 2G
      PUID: '1000'
      PGID: '1000'
      UMASK: '000'
      USER_PASSWORD: ${STEAM_USER_PASSWORD}
      MODE: primary
      WEB_UI_MODE: vnc
      ENABLE_VNC_AUDIO: 'true'
      PORT_NOVNC_WEB: '8083'
      NEKO_NAT1TO1: ''
      ENABLE_SUNSHINE: 'false'
      ENABLE_EVDEV_INPUTS: 'false'
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.12
    mac_address: 96:4a:9f:c8:c6:b9
    volumes:
      - /mnt/zhdd/steam/home:/home/default:rw
      - /mnt/zhdd/steam/games:/mnt/games:rw
