#!/bin/sh

set -e

exec s6-setuidgid '989:989' /usr/bin/ssh -N -i /config/icefox_ssh.key -o ServerAliveInterval=20 -o ServerAliveCountMax=5 -o ConnectTimeout=10 -D 127.0.0.1:5555 proxyuser@icefox.doridian.net
