global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'prometheus.foxden.network'

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['bengalfox.foxden.network:9100', 'islandfox.foxden.network:9100', 'ntp.foxden.network:9100', 'homeassistant.foxden.network:9100', 'router.foxden.network:9100', 'redfox.doridian.net:9100', 'icefox.doridian.net:9100']

  - job_name: telegraf
    static_configs:
      - targets: ['telegraf:9273']

  - job_name: homeassistant
    scrape_interval: 60s
    metrics_path: /api/prometheus
    authorization:
      credentials: '__HOMEASSISTANT_API_TOKEN__'
    scheme: https
    static_configs:
      - targets: ['homeassistant.foxden.network:443']

  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: deluge
    static_configs:
      - targets: ['dldr.foxden.network:9100']
