version: "2.4"
services:
  api:
    image: ghcr.io/doridian/e621dumper/e621dumper:latest
    restart: always
    links:
      - elasticsearch:elasticsearch
    volumes:
      - e621dumper_config:/config
      - /mnt/zhdd/e621/data:/data

volumes:
  e621dumper_config:
    external: true
