version: "2.4"
services:
  api:
    image: ghcr.io/doridian/e621dumper/e621dumper:latest
    restart: always
    links:
      - elasticsearch:elasticsearch
    volumes:
      - e621dumper_config:/config
      - /mnt/zhdd/e621/data:/data
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:8001/api/v1/healthcheck" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  e621dumper_config:
    external: true
