version: "2.4"
services:
  elasticsearch:
    image: elasticsearch:7.16.1
    restart: always
    environment:
      discovery.type: single-node
      network.host: _site_
      network.bind_host: _site_
      xpack.security.enabled: 'false'
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:9200/_cat/health" >/dev/null || exit 1'
      interval: 5s
      timeout: 3s
    volumes:
    - /mnt/zssd/e621/db:/usr/share/elasticsearch/data
