version: "2.4"
services:
  elasticsearch:
    image: elasticsearch:7.14.1
    restart: always
    environment:
      discovery.type: single-node
      network.host: _site_
      network.bind_host: _site_
    volumes:
    - /mnt/zssd/e621/db:/usr/share/elasticsearch/data
