version: "2.1"
services:
  e621dumper:
    image: ghcr.io/doridian/e621dumper/e621dumper:latest
    restart: always
    environment:
      - discovery.type: single-node
      - network.host: _local_
      - network.bind_host: _local_
    volumes:
      - e621dumper_config:/config
      - /mnt/zhdd/e621/data:/data
      - /mnt/zssd/e621/db:/usr/share/elasticsearch/data

volumes:
  e621dumper_config:
    external: true
