services:
  web:
    build: web
    restart: always
    network_mode: service:forgejo
    volumes:
      - web_data:/data
      - web_config:/config
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  web_data: {}
  web_config: {}
