services:
  server:
    image: factoriotools/factorio:latest
    restart: always
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.7
    mac_address: 00:16:3E:CA:7E:06
    volumes:
      - /mnt/zssd/docker/factorio:/factorio
