services:
  server:
    image: factoriotools/factorio:stable
    restart: always
    environment:
      UPDATE_MODS_ON_START: 'true'
    stop_grace_period: 2m
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.7
    volumes:
      - data:/factorio
      - /mnt/tmpfs/factorio-script-output:/factorio/script-output

volumes:
  data: {}
