services:
  server:
    image: ghcr.io/doridian/factorio-docker/factorio:stable
    restart: always
    environment:
      UPDATE_MODS_ON_START: 'true'
      PAUSE_DURING_JOIN: 'true;'
    stop_grace_period: 2m
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.7
    volumes:
      - data:/factorio

volumes:
  data: {}
