defaults:
  backends:
    http:
      host: 127.0.0.1
      port: 9999
    https:
      host: 127.0.0.1
      port: 9998

templates:
  xmpp:
    http:
      host: 192.168.69.4
    https:
      host: 192.168.69.4
  nas-web:
    http:
      host: 192.168.69.5
    https:
      host: 192.168.69.5
  syncthing:
    http:
      host: 192.168.69.6
    https:
      host: 192.168.69.6
  host:
    http:
      host: 192.168.69.254
      port: 180
    https:
      host: 192.168.69.254
      port: 180

hosts:
  foxden.network:
    template: xmpp
  xmpp.foxden.network:
    template: xmpp
  upload.xmpp.foxden.network:
    template: xmpp
  muc.xmpp.foxden.network:
    template: xmpp
  proxy.xmpp.foxden.network:
    template: xmpp
  pubsub.xmpp.foxden.network:
    template: xmpp

  nas-ro.foxden.network:
    template: nas-web

  syncthing.doridian.net:
    template: syncthing

  icefox.doridian.net:
    template: host
# TODO: Fix rest-server SSL renewal
