---
version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
    volumes:
      - akvorado-zookeeper:/bitnami/zookeeper
  kafka:
    image: bitnami/kafka:3.3
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DELETE_TOPIC_ENABLE=true
    restart: unless-stopped
    depends_on:
      - zookeeper
    volumes:
      - akvorado-kafka:/bitnami/kafka
    healthcheck:
      interval: 20s
      timeout: 10s
      retries: 3
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "kafka:9092"]
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - SERVER_SERVLET_CONTEXT_PATH=/kafka-ui

  redis:
    image: bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  akvorado-orchestrator:
    image: ghcr.io/akvorado/akvorado:latest
    restart: unless-stopped
    command: orchestrator /etc/akvorado.yaml
    volumes:
      - ./akvorado.yaml:/etc/akvorado.yaml:ro

  akvorado-console:
    image: ghcr.io/akvorado/akvorado:latest
    restart: unless-stopped
    depends_on:
      - redis
    command: console http://akvorado-orchestrator:8080
    volumes:
      - akvorado-console-db:/run/akvorado
  akvorado-inlet:
    image: ghcr.io/akvorado/akvorado:latest
    networks:
      default:
        priority: 1
      vlan6:
        priority: 100
        ipv4_address: 10.6.11.4
    mac_address: 9e:75:39:c3:13:b3
    restart: unless-stopped
    command: inlet http://akvorado-orchestrator:8080
    volumes:
      - /usr/share/GeoIP:/usr/share/GeoIP:ro
      - akvorado-run:/run/akvorado
    labels:
      - akvorado.conntrack.fix=true
  akvorado-conntrack-fixer:
    image: ghcr.io/akvorado/akvorado:latest
    cap_add:
      - NET_ADMIN
    command: conntrack-fixer
    restart: unless-stopped
    network_mode: host
    healthcheck:
      disable: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  clickhouse:
    image: clickhouse/clickhouse-server:22.8
    volumes:
      - ./orchestrator/clickhouse/data/docker-entrypoint.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - akvorado-clickhouse:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_INIT_TIMEOUT=60
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      test: ["CMD", "wget", "-T", "1", "--spider", "--no-proxy", "http://clickhouse:8123"]

volumes:
  akvorado-zookeeper:
  akvorado-kafka:
  akvorado-clickhouse:
  akvorado-run:
  akvorado-console-db:
