services:
  grafana-web:
    build: grafana-web
    restart: always
    networks:
      default:
        priority: 1
      vlan6:
        priority: 100
        ipv4_address: 10.6.11.3
    mac_address: ba:11:ef:53:38:7a
    volumes:
      - web_data:/data
      - web_config:/config
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  web_data: {}
  web_config: {}
