version: "2.4"
services:
  plex:
    image: plexinc/pms-docker:latest
    restart: always
    networks:
      vlan3:
        ipv4_address: 192.168.3.20
    environment:
      PLEX_UID: 10001
      PLEX_GID: 1001
      ALLOWED_NETWORKS: 192.168.0.0/16
    volumes:
      - plex_data:/config
      - /mnt/zssd/docker/plex/transcode:/transcode
      - /mnt/zhdd/nas:/media
    healthcheck:
      test: 'curl -s -f "http://$${HOSTNAME}:32400/web/index.html" >/dev/null || exit 1'
      interval: 5s
      timeout: 3s

volumes:
  plex_data:
    external: true
