version: "2.4"
services:
  plugin:
    image: rdma/sriov-plugin:latest
    restart: always
    networks:
      host: {}
    userns_mode: host
    privileged: true
    volumes:
      - "/var/run:/var/run"
      - "/run/docker/plugins:/run/docker/plugins"
      - "/etc/docker:/etc/docker"
