services:
  server:
    image: ghcr.io/foxbukkit/packages/server:latest
    restart: always
    environment:
      MAX_MEMORY: 16G
      TZ: America/Los_Angeles
      MAVEN_GITHUB_TOKEN: ${MAVEN_GITHUB_TOKEN}
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.8
    mac_address: 36:16:0c:c9:e8:b0
    volumes:
      - /mnt/zssd/docker/minecraft:/data
