services:
  server:
    image: itzg/minecraft-server:latest
    restart: always
    environment:
      EULA: 'TRUE'
      TYPE: 'PAPER'
      MEMORY: '4G'
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.2
    volumes:
      - data:/data

volumes:
  data: {}
