services:
  server:
    image: marctv/minecraft-papermc-server:1.20
    restart: always
    environment:
      MEMORYSIZE: 16G
      PUID: 1337
      PGID: 1337
      TZ: America/Los_Angeles
    stop_grace_period: 2m
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.8
    mac_address: 36:16:0c:c9:e8:b0
    volumes:
      - data:/data

volumes:
  data: {}
