services:
  server:
    image: itzg/minecraft-server:latest
    restart: always
    environment:
      EULA: 'TRUE'
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.2
    mac_address: 00:16:3e:ca:7e:05
    volumes:
      - /mnt/zssd/docker/minecraft:/data
