services:
  ollama:
    image: ollama/ollama
    restart: always
    init: true
  web:
    init: true
    restart: always
    image: ghcr.io/ivanfioravanti/chatbot-ollama:main
    links:
      - ollama:ollama
    environment:
      OLLAMA_HOST: "http://ollama:11434"
      DEFAULT_MODEL: llama2-uncensored
