services:
  proxy:
    image: ghcr.io/doridian/lan-tunnel-proxy/lan-tunnel-proxy:latest
    restart: always
    init: yes
    ports:
    - 80:80
    - 443:443
    links:
    - redis:redis
    environment:
      REDIS_HOST: redis:6379
