services:
  syncthing:
    image: linuxserver/syncthing:latest
    restart: always
    volumes:
      - config:/config
      - data:/data1
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 8384 || exit 1'
      interval: 60s
      timeout: 10s
  webdav:
    build: webdav
    restart: always
    init: true
    network_mode: service:syncthing
    environment:
      WEBDAV_PASSWORD_DORIDIAN: ${WEBDAV_PASSWORD_DORIDIAN}
    volumes:
    - webdav_config:/config
    - webdav_data:/data
    - data:/syncthing
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  config: {}
  data: {}
