services:
  syncthing:
    image: linuxserver/syncthing:latest
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      vlan2:
        priority: 100
        ipv4_address: 10.2.11.2
    mac_address: ae:fc:dd:8b:33:76
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - config:/config
      - data:/data1
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 8384 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  config: {}
  data: {}
