services:
  webdav:
    build: webdav
    restart: always
    init: true
    environment:
      WEBDAV_PASSWORD_DORIDIAN: ${WEBDAV_PASSWORD_DORIDIAN}
    volumes:
    - webdav_config:/config
    - webdav_data:/data
    - data:/syncthing
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  webdav_config: {}
  webdav_data: {}
