version: "2.4"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${FOXCAVES_POSTGRES_PASSWORD}
    volumes:
      - foxcaves_postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 60s
      timeout: 10s

volumes:
  foxcaves_postgres:
    external: true
