version: "2.4"
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - foxcaves_redis:/data
    healthcheck:
      test: redis-cli PING
      interval: 5s
      timeout: 3s

volumes:
  foxcaves_redis:
    external: true
