version: "2.4"
services:
  site:
    image: ghcr.io/foxcaves/site/foxcaves-site:latest
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      ENVIRONMENT: production
      DDNS_URL_IPV6: ${FOXCAVES_DDNS_URL_IPV6}
    networks:
      default: {}
      vlan2:
        ipv4_address: 192.168.2.25
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - foxcaves_config:/var/www/foxcaves/config
      - /mnt/zhdd/foxcaves/storage:/var/www/foxcaves/storage
    healthcheck:
      test: 'curl -s -f "http://$HOSTNAME/api/v1/system/info" >/dev/null || exit 1'
      interval: 5s
      timeout: 3s

volumes:
  foxcaves_config:
    external: true
