services:
  website:
    image: ghcr.io/doridian/website/website:latest
    restart: always
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
    - config:/config
    - data:/data

volumes:
  config: {}
  data: {}
