services:
  website:
    image: ghcr.io/doridian/website/website:latest
    restart: always
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
    volumes:
    - website_config:/config
    - website_data:/data

volumes:
  website_config: {}
  website_data: {}
