services:
  signtools:
    build: signtools
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.6
    mac_address: f2:fd:df:5c:04:a1
    volumes:
      - signtools_data:/data
      - signtools_config:/config
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 8080 || exit 1'
      interval: 60s
      timeout: 10s
      start_period: 5m
  signtools-web:
    build: signtools-web
    restart: always
    network_mode: service:signtools
    volumes:
      - web_data:/data
      - web_config:/config
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s
      start_period: 5m

volumes:
  signtools_data: {}
  signtools_config: {}
  web_data: {}
  web_config: {}
