services:
  signtools:
    build: signtools
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.6
    volumes:
      - signtools_data:/data
    healthcheck:
      test: 'wget --spider -q "http://$${HOSTNAME}:8080/" >/dev/null || exit 1'
      interval: 60s
      timeout: 10s
  signtools-web:
    build: signtools-web
    restart: always
    network_mode: service:signtools
    volumes:
      - web_data:/data
      - web_config:/config
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 443 || exit 1'
      interval: 60s
      timeout: 10s

volumes:
  signtools_data: {}
  web_data: {}
  web_config: {}
