services:
    fitcrack:
      build: fitcrack
      hostname: ftcr.foxden.network
      command: /custom-entrypoint.sh
      restart: always
      environment:
        - USER=root

        # MySQL database environment variables
        - DB_HOST=localhost
        - DB_NAME=fitcrack
        - DB_USER=fitcrack
        - DB_PW=${MYSQL_PASSWORD}

        # Fitcrack WebAdmin environment variables
        - WEBADMIN_HOST=ftcr.foxden.network
        - WEBADMIN_PROTO=https
        - BACKEND_PORT=5000
        - FRONTEND_PORT=80
        - SSL_WEBADMIN=n
        - WEBADMIN_USER=doridian
        - WEBADMIN_EMAIL=fitcrack@doridian.net
        - WEBADMIN_PW=${FITCRACK_PASSWORD}

        - DYNAMIC_BACKEND_URL=n

        - FITCRACK_SERVER_HOST=ftcr.foxden.network

        # BOINC server environment variables
        - BOINC_HOST=ftcr.foxden.network
        - BOINC_PROTO=https
        - BOINC_PORT=80
        - SSL_BOINCn
        - BOINC_URL=https://ftcr.foxden.network
        - BOINC_USER=boincadm
        - BOINC_GROUP=boincadm
        - BOINC_HOME=/home/boincadm
        - BOINC_PROJECT=fitcrack
        - BOINC_PROJECT_DIR=/home/boincadm/projects/fitcrack
        - OPS_LOGIN=doridian
        - OPS_PW=${FITCRACK_PASSWORD}
        - SERVICE_INSTALL=y
        - PROJECT_HTTPD_CONF=/home/boincadm/projects/fitcrack/fitcrack.httpd.conf

        # SSL certificate file names (used if SSL_WEBADMIN='y' or SSL_BOINC='y')
        - SSL_CERTIFICATE_FILE=ssl.crt
        - SSL_CERTIFICATE_KEYFILE=ssl.key

        # Apache web server environment variables
        - APACHE_USER=www-data                            # Apache web server user
        - APACHE_CONFIG_DIR=/etc/apache2                  # Apache configuration directory
        - APACHE_CONFIG_FILE=/etc/apache2/apache2.conf    # Apache main config file
        - APACHE_DOCUMENT_ROOT=/var/www/html              # Apache document root
        - APACHE_SERVICE=apache2                          # Apach servic name
        - PYTHONUNBUFFERED=1                              # Backend python buffering
      volumes:
        - "ssl:/etc/letsencrypt"

volumes:
  ssl: {}
